sudo: false
language: node_js
node_js:
  - "7"
cache: yarn
services:
  - mongodb
  - redis-server
script:
  - yarn global add codecov
  - yarn coverage
after_success:
  - bash <(curl -s https://codecov.io/bash)
